namespace: wooglife

name: &name polarlight-notifier

cronjob:
  name: *name
  image: "${IMAGE_NAME}:${GITHUB_SHA}"
  schedule: "*/30 * * * *"
  timeZone: "Europe/Berlin"
  backoffLimit: 0
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  restartPolicy: Never
  labels:
    app: *name
  requests:
    cpu: 100m
    memory: 100Mi
  limit:
    cpu: 300m
    memory: 300Mi

secret:
  name: *name
  telegramToken: "${TELEGRAM_TOKEN}"

configmap:
  name: *name
  chatId: "-1001397708243"
  notifierId: "139656428"
  notifyChanceValues: "hoch"
